require( 'sinatra' )
require( 'sinatra/contrib/all' )
require( 'pry' )
require_relative( './models/cover' )
require_relative( './models/customer' )
require_relative( './models/restaurant' )
also_reload( './models/*' )
